import type { NavItem } from '@/types';

import { env } from './env';

/**
 * Single source of truth for the site's identity. Metadata, the header, the
 * footer and OG tags all read from here — change the name once, not in nine
 * places.
 */
export const siteConfig = {
    name: 'Pishon Parts',
    /* The registered entity, for the copyright line and legal pages. */
    legalName: 'Pishon Parts & Machineries Ltd.',
    /* Used verbatim as the default meta description; keep under ~155 chars. */
    description:
        "Connecting Nigeria's natural resources and industrial needs with the global economy through precision and integrity.",
    /* Placeholders — swap for the real contact details before launch. */
    email: 'info@pishonparts.com',
    phone: '+234 000 000 0000',
    url: env.NEXT_PUBLIC_APP_URL,
    /* The share card is generated by `app/opengraph-image.tsx`, so there's no
       static path to configure here. */
    locale: 'en_US',
    creator: '@yourhandle',
    links: {
        github: 'https://github.com/your-org/next-starter-kit',
        twitter: 'https://twitter.com/yourhandle',
    },
} as const;

/**
 * The nav tree. An item with `children` is a disclosure rather than a
 * destination — `NavMenu` opens it beside the main list on desktop and beneath
 * it on mobile, and never navigates to the parent's own `href`.
 */
export const mainNav: readonly NavItem[] = [
    {
        title: 'About',
        href: '/about',
        children: [
            { title: 'Company Overview', href: '/about' },
            { title: 'Why Choose Us', href: '/about/why-choose-us' },
            { title: 'Certifications', href: '/about/certifications' },
        ],
    },
    {
        title: 'Products',
        href: '/products',
        children: [
            { title: 'Agricultural Commodities', href: '/products/agricultural-commodities' },
            { title: 'Solid Minerals', href: '/products/solid-minerals' },
            {
                title: 'Mechanical Parts and Machinery',
                href: '/products/mechanical-parts-and-machinery',
            },
        ],
    },
    { title: 'Services', href: '/services' },
    { title: 'Export Process', href: '/export-process' },
    { title: 'Gallery', href: '/gallery' },
    { title: 'Contact', href: '/contact' },
] as const;

export interface NavGroup {
    title: string;
    items: readonly NavItem[];
}

/** Footer link columns. Separate from `mainNav` — a footer indexes the site far
 *  more densely than the header, and the two drift apart in practice. */
export const footerNav: readonly NavGroup[] = [
    {
        title: 'Company',
        items: [
            { title: 'About Us', href: '/about' },
            { title: 'Our Process', href: '/export-process' },
            { title: 'Compliance', href: '/about/certifications' },
            { title: 'News', href: '/news' },
        ],
    },
    {
        title: 'Products',
        items: [
            { title: 'Agro-Exports', href: '/products/agricultural-commodities' },
            { title: 'Solid Minerals', href: '/products/solid-minerals' },
            { title: 'Machinery Parts', href: '/products/mechanical-parts-and-machinery' },
            { title: 'Industrial Gear', href: '/products' },
        ],
    },
    {
        title: 'Services',
        items: [
            { title: 'Logistics', href: '/services' },
            { title: 'Sourcing', href: '/services' },
            { title: 'Inspection', href: '/services' },
            { title: 'Consulting', href: '/services' },
        ],
    },
    {
        title: 'Legal',
        items: [
            { title: 'Terms of Service', href: '/legal/terms' },
            { title: 'Privacy Policy', href: '/legal/privacy' },
            { title: 'Export Licenses', href: '/legal/licenses' },
        ],
    },
] as const;

export type SiteConfig = typeof siteConfig;
